stars = [
    "avaant",
    "gla",
    "waox",
    "zria",
    "brooms",
    "slepheos",
    "cravion",
    "crokaims",
    "israalix",
    "vreukkec",
    "shib",
    "peus",
    "shuet",
    "xeun",
    "usaps",
    "strectef",
    "clegdiar",
    "icuhlueh",
    "rikloh",
    "rueltas",
    "puct",
    "tho",
    "uyoon",
    "briaf",
    "ma",
    "qeeltok",
    "magsoob",
    "gleoplof",
    "gaicli",
    "clestrih",
    "prios",
    "chauc",
    "teeh",
    "noilt",
    "oplaan",
    "cheagrah",
    "husdealt",
    "brooflep",
    "baewo",
    "flucceur",
    "zlo",
    "ugriuy",
    "vlueb",
    "thoac",
    "wib",
    "coijes",
    "bleutto",
    "zluggaph",
    "motue",
    "qudrith",
    "usheob",
    "zli",
    "strua",
    "eglub",
    "owiact",
    "piotocs",
    "gleikran",
    "plachueg",
    "vefod",
    "gitsont",
    "baps",
    "reolt",
    "stroa",
    "thecs",
    "croif",
    "fioksu",
    "aweado",
    "vlaphei",
    "graokdeb",
    "oqiweays",
    "fliay",
    "yacs",
    "cact",
    "xa",
    "uslaits",
    "gruarop",
    "fainsem",
    "vritsiu",
    "laetrult",
    "nutlat",
    "chap",
    "veesh",
    "ezriy",
    "glean",
    "qi",
    "umusrau",
    "slaizla",
    "vlunsaef",
    "floyioms",
    "slaigro",
    "traeph",
    "qog",
    "agli",
    "kriop",
    "galt",
    "pemmeo",
    "eroazlom",
    "kiustot",
    "srabbaom",
    "xuclum",
    "reos",
    "zlont",
    "tims",
    "bu",
    "criurs",
    "uvlissom",
    "gopdoad",
    "teedsams",
    "estreomd",
    "traezots",
    "ucle",
    "oxuf",
    "aba",
    "ostra",
    "vloct",
    "vuqeim",
    "segraent",
    "xazup",
    "prioplit",
    "icludsex",
    "ifluect",
    "vau",
    "oglals",
    "xua",
    "zlum",
    "wivaec",
    "iglinnic",
    "strearto",
    "eflubdue",
    "evlothei",
    "truaf",
    "daog",
    "ozlu",
    "cup",
    "zrea",
    "gaamdush",
    "opioddip",
    "crisdaut",
    "critsin",
    "luhloil",
    "okreekt",
    "giu",
    "zret",
    "fleuk",
    "vea",
    "boprioys",
    "uqefih",
    "uthappum",
    "cheubrum",
    "flebbaos",
]
